/* Include file for io port reg definitions */

	.equ PORTA , 0x00
	.equ PIOC  , 0x02
	.equ PORTC , 0x03
	.equ PORTB , 0x04
	.equ PORTCL, 0x05
	.equ DDRC  , 0x07
	.equ PORTD , 0x08
	.equ DDRD  , 0x09
	.equ PORTE , 0x0A

/* PIOC bits */

	.equ PIOC_INVB_BIT   ,0 /*  */
	.equ PIOC_EGA_BIT    ,1
	.equ PIOC_PLS_BIT    ,2
	.equ PIOC_OIN_BIT    ,3
	.equ PIOC_HNDS_BIT   ,4
	.equ PIOC_CWOM_BIT   ,5
	.equ PIOC_STAI_BIT   ,6
	.equ PIOC_STAF_BIT   ,7


